### ISSUE TITLE
Styles not applied

### ISSUE THREAD

**Issue by anesumuz** [HsuanXyz/ionic-tags-input#9]
I've added the package with `npm install ionic-tags-input --save` and imported the module. I've also set up the event handler and included the component in the html file of my Component, but it seems the styles of the input are not shown.

![image](https://user-images.githubusercontent.com/17691094/31546338-2d334f02-b023-11e7-93da-c3de070ed4b8.png)

My environment

 ```
@ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 1.3.4
    Ionic Framework    : ionic-angular 3.1.1

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Misc:

```

**Comment by HsuanXyz** [comment]
try clear caches.

**Comment by tekkenking** [comment]
same issue.

**Comment by tekkenking** [comment]
Cache clearing resolved the issue.. Thanks for the wonderful job
